/* Generated By:JavaCC: Do not edit this line. MeuphoriaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MeuphoriaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMENTARIO_INICIAL = 5;
  /** RegularExpression Id. */
  int COMENTARIO_LINHA = 6;
  /** RegularExpression Id. */
  int COMENTARIO_BLOCO = 7;
  /** RegularExpression Id. */
  int AND = 8;
  /** RegularExpression Id. */
  int CASE = 9;
  /** RegularExpression Id. */
  int DO = 10;
  /** RegularExpression Id. */
  int END = 11;
  /** RegularExpression Id. */
  int EXPORT = 12;
  /** RegularExpression Id. */
  int GLOBAL = 13;
  /** RegularExpression Id. */
  int INCLUDE = 14;
  /** RegularExpression Id. */
  int NOT = 15;
  /** RegularExpression Id. */
  int PUBLIC = 16;
  /** RegularExpression Id. */
  int SWITCH = 17;
  /** RegularExpression Id. */
  int UNTIL = 18;
  /** RegularExpression Id. */
  int XOR = 19;
  /** RegularExpression Id. */
  int AS = 20;
  /** RegularExpression Id. */
  int CONSTANT = 21;
  /** RegularExpression Id. */
  int ELSE = 22;
  /** RegularExpression Id. */
  int ENTRY = 23;
  /** RegularExpression Id. */
  int FALLTHRU = 24;
  /** RegularExpression Id. */
  int GOTO = 25;
  /** RegularExpression Id. */
  int LABEL = 26;
  /** RegularExpression Id. */
  int OR = 27;
  /** RegularExpression Id. */
  int RETRY = 28;
  /** RegularExpression Id. */
  int THEN = 29;
  /** RegularExpression Id. */
  int WHILE = 30;
  /** RegularExpression Id. */
  int BREAK = 31;
  /** RegularExpression Id. */
  int CONTINUE = 32;
  /** RegularExpression Id. */
  int ELSEDEF = 33;
  /** RegularExpression Id. */
  int ENUM = 34;
  /** RegularExpression Id. */
  int IF = 35;
  /** RegularExpression Id. */
  int LOOP = 36;
  /** RegularExpression Id. */
  int OVERRIDE = 37;
  /** RegularExpression Id. */
  int RETURN = 38;
  /** RegularExpression Id. */
  int TO = 39;
  /** RegularExpression Id. */
  int WITH = 40;
  /** RegularExpression Id. */
  int BY = 41;
  /** RegularExpression Id. */
  int DEPRECATE = 42;
  /** RegularExpression Id. */
  int ELSIF = 43;
  /** RegularExpression Id. */
  int EXIT = 44;
  /** RegularExpression Id. */
  int FUNCTION = 45;
  /** RegularExpression Id. */
  int IFDEF = 46;
  /** RegularExpression Id. */
  int NAMESPACE = 47;
  /** RegularExpression Id. */
  int PROCEDURE = 48;
  /** RegularExpression Id. */
  int ROUTINE = 49;
  /** RegularExpression Id. */
  int TYPE = 50;
  /** RegularExpression Id. */
  int WITHOUT = 51;
  /** RegularExpression Id. */
  int LPAREN = 52;
  /** RegularExpression Id. */
  int RPAREN = 53;
  /** RegularExpression Id. */
  int LBRACE = 54;
  /** RegularExpression Id. */
  int RBRACE = 55;
  /** RegularExpression Id. */
  int LBRACKET = 56;
  /** RegularExpression Id. */
  int RBRACKET = 57;
  /** RegularExpression Id. */
  int SEMICOLON = 58;
  /** RegularExpression Id. */
  int COMMA = 59;
  /** RegularExpression Id. */
  int DOT = 60;
  /** RegularExpression Id. */
  int QUOTE = 61;
  /** RegularExpression Id. */
  int ASSIGN = 62;
  /** RegularExpression Id. */
  int GT = 63;
  /** RegularExpression Id. */
  int LT = 64;
  /** RegularExpression Id. */
  int BANG = 65;
  /** RegularExpression Id. */
  int TILDE = 66;
  /** RegularExpression Id. */
  int HOOK = 67;
  /** RegularExpression Id. */
  int COLON = 68;
  /** RegularExpression Id. */
  int EQ = 69;
  /** RegularExpression Id. */
  int LE = 70;
  /** RegularExpression Id. */
  int GE = 71;
  /** RegularExpression Id. */
  int NE = 72;
  /** RegularExpression Id. */
  int SC_OR = 73;
  /** RegularExpression Id. */
  int SC_AND = 74;
  /** RegularExpression Id. */
  int INCR = 75;
  /** RegularExpression Id. */
  int DECR = 76;
  /** RegularExpression Id. */
  int PLUS = 77;
  /** RegularExpression Id. */
  int MINUS = 78;
  /** RegularExpression Id. */
  int STAR = 79;
  /** RegularExpression Id. */
  int SLASH = 80;
  /** RegularExpression Id. */
  int BIT_AND = 81;
  /** RegularExpression Id. */
  int BIT_OR = 82;
  /** RegularExpression Id. */
  int XOR_OP = 83;
  /** RegularExpression Id. */
  int REM = 84;
  /** RegularExpression Id. */
  int LSHIFT = 85;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 86;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 87;
  /** RegularExpression Id. */
  int PLUSASSIGN = 88;
  /** RegularExpression Id. */
  int MINUSASSIGN = 89;
  /** RegularExpression Id. */
  int STARASSIGN = 90;
  /** RegularExpression Id. */
  int SLASHASSIGN = 91;
  /** RegularExpression Id. */
  int ANDASSIGN = 92;
  /** RegularExpression Id. */
  int ORASSIGN = 93;
  /** RegularExpression Id. */
  int XORASSIGN = 94;
  /** RegularExpression Id. */
  int REMASSIGN = 95;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 96;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 97;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 98;
  /** RegularExpression Id. */
  int USCORE = 99;
  /** RegularExpression Id. */
  int ALPHA = 100;
  /** RegularExpression Id. */
  int DIGITO = 101;
  /** RegularExpression Id. */
  int ID = 102;
  /** RegularExpression Id. */
  int INT = 103;
  /** RegularExpression Id. */
  int FLOAT = 104;
  /** RegularExpression Id. */
  int STRING = 105;
  /** RegularExpression Id. */
  int DATATYPE = 106;
  /** RegularExpression Id. */
  int NAME = 107;
  /** RegularExpression Id. */
  int SPACENAME = 108;
  /** RegularExpression Id. */
  int IDENTIFIER = 109;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<COMENTARIO_INICIAL>",
    "<COMENTARIO_LINHA>",
    "<COMENTARIO_BLOCO>",
    "\"and\"",
    "\"case\"",
    "\"do\"",
    "\"end\"",
    "\"export\"",
    "\"global\"",
    "\"include\"",
    "\"not\"",
    "\"public\"",
    "\"switch\"",
    "\"until\"",
    "\"xor\"",
    "\"as\"",
    "\"constant\"",
    "\"else\"",
    "\"entry\"",
    "\"fallthru\"",
    "\"goto\"",
    "\"label\"",
    "\"or\"",
    "\"retry\"",
    "\"then\"",
    "\"while\"",
    "\"break\"",
    "\"continue\"",
    "\"elsedef\"",
    "\"enum\"",
    "\"if\"",
    "\"loop\"",
    "\"override\"",
    "\"return\"",
    "\"to\"",
    "\"with\"",
    "\"by\"",
    "\"deprecate\"",
    "\"elsif\"",
    "\"exit\"",
    "\"function\"",
    "\"ifdef\"",
    "\"namespace\"",
    "\"procedure\"",
    "\"routine\"",
    "\"type\"",
    "\"without\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"\\\"\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"_\"",
    "<ALPHA>",
    "<DIGITO>",
    "<ID>",
    "<INT>",
    "<FLOAT>",
    "<STRING>",
    "<DATATYPE>",
    "<NAME>",
    "<SPACENAME>",
    "<IDENTIFIER>",
  };

}
